# -*- coding: utf-8 -*-
"""sdxl-batch-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvN_CJGGAy1pEdJiKg7CeZVQakpC6aDs
"""

import os
import zipfile
from datetime import datetime

!pip install -q diffusers transformers accelerate safetensors

import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True
).to("cuda")

pipe.enable_attention_slicing()

# prompt = "3D orange fox wearing glasses typing on a laptop, clean white background"

# image = pipe(prompt, num_inference_steps=30).images[0]
# image

prompts = [
  "A real photo of a vintage adding machine with a paper tape showing a total of 'R0' and a green plus sign, isolated on cream background, soft studio lighting --ar 1:1",
  "A real close-up of a rubber stamp pressed into an ink pad, the stamp says 'APPROVED', plain white surface, natural light --ar 1:1",
  "A real photograph of a classic library card catalog drawer pulled open, inside is a single card with a checkmark, beige background, soft shadows --ar 1:1",
  "A real photo of a manual pencil sharpener with a single sharpened pencil beside it, the pencil tip is perfect, isolated on light grey, studio shot --ar 1:1",
  "A real vintage cash drawer slightly pulled open, a single folded receipt visible inside, plain wood surface, natural daylight --ar 1:1",
  "A real photo of a car odometer showing low mileage, a small green leaf sticker next to it, clean dashboard background, soft light --ar 1:1",
  "A real close-up of a wall-mounted telephone with a notepad hanging below, the notepad has a single checkmark, plain wall background --ar 1:1",
  "A real photograph of a desktop inbox tray, one single paper inside labeled 'Lead', the rest empty, grey office background, overhead shot --ar 1:1",
  "A real photo of a vending machine button being pressed, the button says 'Solve', machine face plain, neutral background, soft light --ar 1:1",
  "A real close-up of a combination lock that is open hanging on a briefcase, briefcase slightly ajar, plain surface, natural light --ar 1:1",
  "A real photograph of a classic hole punch over a single paper with a clean hole, isolated on white, overhead studio lighting --ar 1:1",
  "A real photo of a cash register receipt slowly printing, the printed line reads 'Paid in Full', neutral background, soft focus --ar 1:1",
  "A real vintage wall clock showing exactly 5:00 (quitting time), isolated on light grey, clean product shot --ar 1:1",
  "A real photo of a clean whiteboard with three bullet points drawn: a plug (slash through it), an eye (checkmark), a dollar sign (arrow up), office background --ar 1:1",
  "A real close-up of a red wax seal on an envelope, the seal has a simple checkmark imprint, cream paper, soft shadows --ar 1:1",
  "A real photograph of a classic desk nameplate that says 'Closed', empty desk background, soft office lighting --ar 1:1",
  "A real photo of a single key being inserted into a lock, the lock has a small green dot on it, plain surface, natural light --ar 1:1",
  "A real close-up of a thermostat set to a comfortable temperature, a small smiley face sticker beside it, plain wall background --ar 1:1",
  "A real photograph of a vintage cash box open and empty, a single gold coin placed inside, dark wood surface, soft light --ar 1:1",
  "A real photo of a badge or ID card with a gold star sticker on it, the card is blank except the star, plain surface, natural light --ar 1:1"
]

images = []
i = 0
for p in prompts:
    img = pipe(p, num_inference_steps=30).images[0]
    img.save(f"/content/Untitled Folder 1/output_{i}.png")
    i += 1
    # images.append(img)
    # img

images

# for i, img in enumerate(images):
#     img.save(f"/content/Untitled Folder/output_{i}.png")

import zipfile
import os

# Replace 'your_folder_path' with your actual folder
folder_to_zip = '/content/Untitled Folder'
zip_path = '/content/generated-images-1.zip'

with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(folder_to_zip):
        for file in files:
            zipf.write(os.path.join(root, file),
                       os.path.relpath(os.path.join(root, file),
                                       os.path.join(folder_to_zip, '..')))

# Then download the zip file
from google.colab import files
files.download(zip_path)